config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'plans#index'
  resources :plans do
    resources :items, only: [:new, :create, :destroy, :edit, :update] do
      resources :details, only: [:new, :create, :show, :destroy, :edit, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :item

  validates :title, :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :plan
  has_many :details, dependent: :destroy

  validates :title, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans, dependent: :destroy

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :show]
  before_action :set_detail, only: [:show, :destroy, :edit, :update]

  def new
    @detail = Detail.new
  end

  def create
    @detail = Detail.new(detail_params)
    if @detail.save
      redirect_to plan_path(params[:plan_id])
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @detail.destroy
    redirect_to plan_path(@detail.item.plan.id)
  end

  def edit
    @items = Item.where(plan_id: params[:plan_id])
  end

  def update
    if @detail.update(detail_params)
      redirect_to plan_item_detail_path(@detail.item.plan.id, @detail.item.id, @detail.id)
    else
      render :edit
    end
  end

  private

  def detail_params
    params.require(:detail).permit(:title, :text, :item_id)
  end

  def set_detail
    @detail = Detail.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_item, only: [:edit, :update, :destroy]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to plan_path(@item.plan)
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to plan_path(@item.plan.id)
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to plan_path(@item.plan.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:title).merge(plan_id: params[:plan_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :edit]
  before_action :set_plan, only: [:edit, :update, :show, :destroy]

  def index
    @plans = Plan.includes(:user)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @plan.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  end

  private

  def plan_params
    params.require(:plan).permit(:title).merge(user_id: current_user.id)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true
    }

    extensions = {
      tables: true,
      fenced_code_blocks: true,
      autolink: true,
      strikethrough: true,
      lax_spacing: true,
      space_after_headers: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/details/edit.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>詳細変更</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @detail, url: { action: :update }, local: true do |f| %>

      <div class="field">
        <%= f.label '詳細概要' %><br /><br />
        <%= f.text_field :title, placeholder: '詳細概要を入力してください', autofocus: true %>
      </div>

      <div class="field">
        <%= f.label '詳細内容' %><br /><br />
        <%= f.text_area :text, placeholder: '詳細内容を入力してください' %>
      </div>

      <div class="field">
        <%= f.label '項目' %><br /><br />
        <%= f.select :item_id, @items.map{ |i| [i.title, i.id] } %>
      </div>

      <div class="actions">
        <%= f.submit "詳細編集", class: 'submit_btn' %>
      </div>
    <% end %>

    <div class='back_btn'>
      <%= link_to plan_item_detail_path(@detail.item.plan.id, @detail.item.id, @detail.id) do %>
        <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
      <% end %>
    </div>

  </div>
</div>

app/views/details/new.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>詳細内容追加</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @detail, url: { action: :create }, local: true do |f| %>

      <div class="field">
        <%= f.label '詳細概要' %><br /><br />
        <%= f.text_field :title, placeholder: '詳細の概要を入力してください', autofocus: true %>
      </div>

      <div class="field">
        <%= f.label '詳細内容' %><br /><br />
        <%= f.text_area :text, placeholder: '詳細内容を入力してください' %>
      </div>

      <%= f.hidden_field :item_id, value: params[:item_id] %>

      <div class="actions">
        <%= f.submit "詳細を追加", class: 'submit_btn' %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/details/show.html.erb
<%= render 'layouts/header' %>

<div class='detail_show_wrapper'>
  <div><%= 'タイトル：' %></div>
  <div class='detail_show_content'>
    <p><%= @detail.item.plan.title %></p>
  </div>
  <div><%= '項目：' %></div>
  <div class='detail_show_content'>
    <p><%= @detail.item.title %></p>
  </div>
  <div><%= '詳細概要：' %></div>
  <div class='detail_show_content'>
    <p><%= @detail.title %></p>
  </div>
  <div><%= '詳細内容：' %></div>
  <div class='detail_text'>
    <p><%= markdown(@detail.text) %></p>
  </div>
  <div class='detail_btn'>
    <%= link_to '編集', edit_plan_item_detail_path(@detail.item.plan.id, @detail.item.id, @detail.id), class: 'edit_btn' %>
    <%= link_to '削除', plan_item_detail_path(@detail.item.plan.id, @detail.item.id, @detail.id), method: :delete, class: 'delete_btn' %>
  </div>
  <div class='back_btn'>
    <%= link_to plan_path(@detail.item.plan.id) do %>
      <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>アイテム名変更</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @item, url: { action: :update }, local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br /><br />
        <%= f.text_field :title, placeholder: 'アイテム名を入力してください', autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "アイテム編集", class: 'submit_btn' %>
      </div>
    <% end %>

    <div class='back_btn'>
      <%= link_to plan_path(@item.plan.id) do %>
        <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
      <% end %>
    </div>

  </div>
</div>

app/views/items/new.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>アイテム新規作成</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @item, url: { action: :create }, local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br /><br />
        <%= f.text_field :title, placeholder: 'アイテムを入力してください', autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "アイテム作成", class: 'submit_btn' %>
      </div>

    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class='header_nav'>
    <ul class='nav_menu'>
      <li class='nav_menu_title'><%= link_to 'PlanDesign', root_path %></li>
      <li>
        <ul class="nav_menu_item">
          <% if user_signed_in? %>
            <li class='nav_link'><%= link_to '新規作成', new_plan_path %></li>
            <li class='nav_link'><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class='nav_link'><%= link_to '新規登録', new_user_registration_path %></li>
            <li class='nav_link'><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanDesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>プラン名変更</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @plan, local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br /><br />
        <%= f.text_field :title, placeholder: 'プランを入力してください', autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "プラン編集", class: 'submit_btn' %>
      </div>
    <% end %>

    <div class='back_btn'>
      <%= link_to root_path do %>
        <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
      <% end %>
    </div>
    
  </div>
</div>

app/views/plans/index.html.erb
<%= render 'layouts/header' %>

<div class='index_main'>
  <% if user_signed_in? %>
    <% @plans.each do |plan| %>
      <div class='index_item'>
        <div class='index_item_title'>
          <%= link_to plan.title, plan_path(plan), class: 'index_show_link' %>
          <br />
          <%= link_to new_plan_item_path(plan), class: 'index_fa' do %>
            <i class="fa fa-plus-square-o" aria-hidden="true"> アイテム作成</i>
          <% end %>
        </div>
        <div class='plan_nav'>
          <%= link_to edit_plan_path(plan) do %>
            <i class="fa fa-edit fa-lg" aria-hidden="true"></i>
          <% end %>
          <%= link_to plan_path(plan), method: :delete do %>
            <i class="fa fa-trash-o fa-lg"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/plans/new.html.erb
<%= render 'layouts/header' %>

<div class='post_wrapper_plan'>
  <div class='post_title'>
    <h1>プラン新規作成</h1>
  </div>
  <div class='post_container'>
    <%= form_with model: @plan, local: true do |f| %>

      <div class="field">
        <%= f.label :title %><br /><br />
        <%= f.text_field :title, placeholder: 'プランを入力してください', autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "プラン作成", class: 'submit_btn' %>
      </div>

      <div class='back_btn'>
        <%= link_to root_path do %>
          <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/plans/show.html.erb
<%= render 'layouts/header' %>

<div class='show_main'>
  <div class='show_wrapper'>
    <div class='show_title'>
      <span><%= @plan.title %></span>
      <div class='back_btn'>
        <%= link_to new_plan_item_path(@plan.id), class: 'show_fa' do %>
          <i class="fa fa-plus-square-o" aria-hidden="true"> アイテム追加</i>
        <% end %>
        <%= link_to plans_path do %>
          <i class="fa fa-hand-o-left" aria-hidden="true"></i>戻る
        <% end %>
      </div>
    </div>
    <div class='show_item_wrapper'>
      <% @plan.items.each do |plan_item| %>
        <div class='show_item_container'>
          <div class='show_item_title'>
            <%= plan_item.title %>
            <div>
              <%= link_to edit_plan_item_path(@plan.id, plan_item.id) do %>
                <i class="fa fa-edit fa-lg" aria-hidden="true"></i>
              <% end %>
              <%= link_to plan_item_path(@plan.id, plan_item.id), method: :delete do %>
                <i class="fa fa-trash-o fa-lg"></i>
              <% end %>
            </div>
          </div>
          <div>
            <% plan_item.details.each do |item_detail| %>
              <%= link_to plan_item_detail_path(@plan.id, plan_item.id, item_detail.id) do %>
                <div class='show_detail'>
                  <%= item_detail.title %><br />
                  <i class="fa fa-bars" aria-hidden="true"></i>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class='show_detail_link'>
            <i class="fa fa-sticky-note-o" aria-hidden="true"></i>
            <%= link_to '詳細登録', new_plan_item_detail_path(@plan.id, plan_item.id) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>